apiVersion: v1
kind: Pod
metadata:
  labels:
    app: gitops
  name: demo-gitops
  namespace: default
spec:
  # securityContext:
  #   runAsUser: 0
  #   runAsGroup: 0
  hostAliases:
  - ip : "192.168.50.225"
    hostnames:
    - "cluster-endpoint"
  containers:
  - command:
    - sh
    - -c
    - /gitops.sh
    image: kubectl:v1.0
    imagePullPolicy: IfNotPresent
    env:
    - name: GITSOURCE
      value: "http://git.harmonycloud.cn/gitops/kube-gitops.git"
    - name: GITPATH
      value: "test/"
    - name: CALLBACK
      value: "http://10.96.221.127:8060/dingtalk/webhook1/send"
    name: gitops
    resources:
      limits:
        cpu: 2
        memory: 400Mi      
      requests:
        cpu: 1
        memory: 200Mi
    volumeMounts:
    - mountPath: /root/.kube
      name: kubeconfig
      readOnly: true
  restartPolicy: Never
  nodeSelector: 
    kubernetes.io/hostname: k8s-master
  tolerations:
  - effect: NoSchedule
    operator: Exists
  volumes:
  - hostPath:
      path: /root/.kube
      type: DirectoryOrCreate
    name: kubeconfig